### ISSUE TITLE
TypeError: in method 'Menu_Append', expected argument 2 of type 'int'

### ISSUE THREAD

**Issue by KarlZeilhofer** [HiGregSmith/LayerViewSet#2]
That's the new message I get:
```
Traceback (most recent call last):

  File "/usr/share/kicad/scripting/plugins/layerviewset.py", line 427, in Run
    self._lvset_frame=gui(self,parent)

  File "/usr/share/kicad/scripting/plugins/layerviewset.py", line 56, in __init__
    super(gui,self).__init__(parent_frame)#, *args, **kw)

  File "/usr/share/kicad/scripting/plugins/layerviewset_gui.py", line 61, in __init__
    self.m_menu3.Append( self.m_menuItem5 )

  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 12003, in Append
    return _core_.Menu_Append(*args, **kwargs)

TypeError: in method 'Menu_Append', expected argument 2 of type 'int'
```

Linux Mint 18.1

```
Application: kicad
Version: 5.0.0-rc2-dev-unknown-5d71153~64~ubuntu16.04.1, release build
Libraries:
    wxWidgets 3.0.2
    libcurl/7.56.1 mbedTLS/2.6.0 zlib/1.2.8
Platform: Linux 4.10.0-40-generic x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.2 (wchar_t,wx containers,compatible with 2.8) GTK+ 2.24
    Boost: 1.58.0
    Curl: 7.47.0
    Compiler: GCC 5.4.0 with C++ ABI 1009

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=OFF
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_WXPYTHON=OFF
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_SPICE=ON
```

**Comment by HiGregSmith** [comment]
My KiCad installation reports using wxWidgets 3.0.2. Perhaps upgrading to 3.0.3 would fix this?

Also, I'm using 5.0.0-rc2-dev-659-g1f5b575ea

**Comment by bvacaliuc** [comment]
Same issue but on KiCad 4.0.7 *(is it expected to work < 5.0?)* with wxWidgets 3.0.3
```
Application: kicad
Version: 4.0.7 release build
wxWidgets: Version 3.0.3 (debug,wchar_t,compiler with C++ ABI 1011,GCC 7.1.0,wx containers,compatible with 2.8)
Platform: Windows 7 (build 7601, Service Pack 1), 64-bit edition, 64 bit, Little endian, wxMSW
Boost version: 1.60.0
Curl version: libcurl/7.54.1 OpenSSL/1.0.2l zlib/1.2.11 libssh2/1.8.0 nghttp2/1.23.1 librtmp/2.3
         USE_WX_GRAPHICS_CONTEXT=OFF
         USE_WX_OVERLAY=OFF
         KICAD_SCRIPTING=ON
         KICAD_SCRIPTING_MODULES=ON
         KICAD_SCRIPTING_WXPYTHON=ON
         USE_FP_LIB_TABLE=HARD_CODED_ON
         BUILD_GITHUB_PLUGIN=ON
```
Doesn't look good; same issue as [this](https://github.com/dougthor42/wafer_map/issues/35) but that ended up resolving with some specially-built wheel file that is no longer available.
